#!/bin/bash

usage(){
  echo "============================================================================="
  echo "USAGE: $0 COMMAND [args]"
  echo "  Command list:"
  echo "    - info        : execute info scripts"
  echo "    - shell       : execute shell scripts"
  echo "    - start       : execute start scripts"
  echo "    - status      : execute status scripts"
  echo "    - npm         : Package manager for JavaScript"
  echo "    - node        : JavaScript runtime built on Chrome's V8 JavaScript engine"
  echo "============================================================================="
}

usage
